if: branch = ci
language: python
os: linux
dist: xenial
apt:
  packages:
  - mercurial
python:
  - "3.7"
  # - "3.8"
  # - "3.9"
  # - "3.10"
install:
  - pip install poetry
  - poetry install
  - echo git_executable=git >> pytest.ini
  - echo hg_executable=hg >> pytest.ini
script:
  - poetry run pytest