skip_non_tags: true
configuration: Release
image: Visual Studio 2022
build: off
environment:
  HGUSER: test
  EMAIL: test@example.com
install:
  - pip install poetry
  - poetry install
  - echo git_executable=C:\Program Files\Git\cmd\git.exe >> pytest.ini
  - echo hg_executable=C:\Program Files\Mercurial\hg.exe >> pytest.ini
  - cat pytest.ini
  - git config --global user.name "test"
  - git config --global user.email "test@example.com"
test_script:
  - poetry run pytest
